version: '2'

services:
  php:
    image: php:7.1-fpm
    privileged: true
    expose:
      - 9000
    volumes:
      - .:/usr/share/nginx/www

  nginx:
    image: nginx:1.21.6
    ports:
      - 4321:80
    depends_on:
      - php
    volumes:
      - ./log/nginx_logs:/var/log/nginx
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - .:/home/wwwroot/web/dist
